/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import leetcode.solution.LevelOrder2Solution;
import java.util.List;

public class App {
    public static void main(String[] args) {
        BaseSolution<List<List<Integer>>> solution = new LevelOrder2Solution();
        solution.performSingleTest();
    }
}
