/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import leetcode.model.TreeNode;
import leetcode.solution.MirrorTreeSolution;

public class App {
    public static void main(String[] args) {
        BaseSolution<TreeNode> solution = new MirrorTreeSolution();
        solution.performSingleTest();
    }
}
