/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import leetcode.model.ListNode;
import leetcode.solution.MergeTwoListsSolution;
import leetcode.util.Printer;

public class App {
    public static void main(String[] args) {
        BaseSolution<ListNode> solution = new MergeTwoListsSolution();
        ListNode result = solution.performSingleTest();
        Printer.printLinkedList(result);
    }
}
